image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - yarn install
    - yarn build
    - mv dist public
    - npm install netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
